name: UI test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo '${{ toJSON(github) }}'
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test:ci
